services:
  story-finisher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: story-finisher-app
    enviroment:
      - GROQ_API_KEY=${GROQ_API_KEY}            
    volumes:
      - ./src:/app/src
    restart: unless-stopped  