apiVersion: v1
kind: Service
metadata:
  name: story-finisher-Service
  labels:
    app: stoy-finisher

specs:
  type: ClusterIP
  selector:
    app: story-finisher
  ports:
     - protocol: TCP
       port: 8000
       targetPort: 8000  
    